-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceExtendedStatistics/maintenance/db/sql/bs_extendedstatistics_snapshot.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_extendedstatistics_snapshot (
  ess_type VARCHAR(255) NOT NULL,
  ess_interval VARCHAR(255) NOT NULL,
  ess_data TEXT NOT NULL,
  ess_secondary_data TEXT NOT NULL,
  ess_timestamp TIMESTAMPTZ NOT NULL
);
