-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpiceExtendedStatistics/maintenance/db/sql/bs_extendedstatistics_snapshot.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_extendedstatistics_snapshot (
  ess_type VARCHAR(255) NOT NULL,
  ess_interval VARCHAR(255) NOT NULL,
  ess_data LONGBLOB NOT NULL,
  ess_secondary_data LONGBLOB NOT NULL,
  ess_timestamp BINARY(14) NOT NULL
) /*$wgDBTableOptions*/;
